Adding alot of error checking

diff --git a/daily-run b/daily-run
--- a/daily-run
+++ b/daily-run
@@ -61,13 +61,18 @@ remove_build-media(){
 add_ssh_keys(){
     # Make this use zenity to get password
     $CD_SSH
-    ssh-add identity
+    if [ -f identity ]; then
+	ssh-add identity
+    else
+	echo "Your identity file could not be located"
+    fi 
     $CDHOME
 }
 
 setup_cron(){
 # Move this code to constants after getting it to work     
 echo "* * * * * export DISPLAY=:0 && export SSH_AUTH_SOCK=$SSH_AUTH && ~/lcsee-scripts/nagios-check" >> ~/mycron
+# Add code to remove existing cron if I can get this working
 crontab -l > ~/mycron
 crontab ~/mycron
 }
@@ -85,7 +90,11 @@ check_nagios001(){
 # method to cp .bashrc into place
 copy_bashrc(){
     $CD_MEDIA
-    $CP_BASHRC
+    if [ -f .bashrc ]; then 
+	$CP_BASHRC
+    else
+	echo ".bashrc could not be located on USB"
+    fi
     $CDHOME
 }
 
@@ -97,7 +106,11 @@ configure_gkeys(){
 
 startup_run(){
     $CD_MEDIA
-    $STARTUP
+    if [ -f startup-run ]; then
+	$STARTUP
+    else
+	echo "Startup file could not be located on USB"
+    fi 
     $CDHOME
 }
 
@@ -118,6 +131,9 @@ tput setaf 4;echo "########################################"; tput sgr0
 tput setaf 3;echo "Checking your SSH Keys"; tput sgr0
 if [ "$(ssh-add -L | grep "The agent has no identities.")" == "The agent has no identities." ]; then
     add_ssh_keys
+       if [ $? == 1 ]; then
+	   echo "ssh-add failed to add your SSH keys correctly - check permissions"
+       fi
 fi
 tput setaf 2;echo "SSH Keys have been loaded"; tput sgr0
 tput setaf 4;echo "########################################"; tput sgr0
