Removing installation of auth packages

diff --git a/provisionsysstaff b/provisionsysstaff
--- a/provisionsysstaff
+++ b/provisionsysstaff
@@ -1,8 +1,8 @@
 #! /usr/bin/env bash
 
-tput setaf 3;echo "Installing SSHpass"; tput sgr0
-sudo apt-get install sshpass
-tput setaf 2;echo "SSHpass Installed"; tput sgr0
+#tput setaf 3;echo "Installing SSHpass"; tput sgr0
+#sudo apt-get install sshpass
+#tput setaf 2;echo "SSHpass Installed"; tput sgr0
 #########################################
 machine_name=$(zenity --entry --title "Ansible Provisioning?" --text="Enter an IP that you would like to provision" --entry-text "IP Address")
 tput setaf 3;echo "Provisioning the machine of your choice"; tput sgr0
@@ -25,57 +25,57 @@ ssh-keygen -f "/home/cumorris/.ssh/known_hosts" -R ${machine_name}
 #    exit
 #fi
 
-tput setaf 3;echo "Installing Sysstaff Auth"; tput sgr0
-echo " "
-sshpass -p "loud" ssh -t -o stricthostkeychecking=no loud@$machine_name "sudo apt-get install lcsee-sysstaff-auth lcsee-senior-auth -y"
+#tput setaf 3;echo "Installing Sysstaff Auth"; tput sgr0
+#echo " "
+#sshpass -p "loud" ssh -t -o stricthostkeychecking=no loud@$machine_name "sudo apt-get install lcsee-sysstaff-auth lcsee-senior-auth -y"
+#
+#RESULT=$?
+#if [ $RESULT -eq 0 ]; then
+#    echo ""
+#else
+#    tput setaf 3;echo "Machine has already been provisioned before"; tput sgr0
+#    ssh -At -o stricthostkeychecking=no cumorris@$machine_name "sudo apt-get install lcsee-sysstaff-auth lcsee-senior-auth -y"#
 
-RESULT=$?
-if [ $RESULT -eq 0 ]; then
-    echo ""
-else
-    tput setaf 3;echo "Machine has already been provisioned before"; tput sgr0
-    ssh -At -o stricthostkeychecking=no cumorris@$machine_name "sudo apt-get install lcsee-sysstaff-auth lcsee-senior-auth -y"
-
-RESULT_2=$?
-if [ $RESULT_2 -eq 0 ]; then
-	echo ""
-else
-    echo " " 
-    tput setaf 1;echo "I can't connect to the machine with user or loud ssh keys"; tput sgr0
-    tput setaf 1;echo "I am going to nmap the machine to tell you if it is up"; tput sgr0
-    nmap ${machine_name} | grep "Host is up" -A1
-    tput setaf 1; echo "Good luck determining the problem br0, my job here is done"; tput sgr0
-    echo " " 
-    exit
-fi
-fi
-tput setaf 2;echo "Sysstaff auth Installed"; tput sgr0
+#RESULT_2=$?
+#if [ $RESULT_2 -eq 0 ]; then
+#	echo ""
+#else
+#    echo " " 
+#    tput setaf 1;echo "I can't connect to the machine with user or loud ssh keys"; tput sgr0
+#    tput setaf 1;echo "I am going to nmap the machine to tell you if it is up"; tput sgr0
+#    nmap ${machine_name} | grep "Host is up" -A1
+#    tput setaf 1; echo "Good luck determining the problem br0, my job here is done"; tput sgr0
+#    echo " " 
+#    exit
+#fi
+#fi
+#tput setaf 2;echo "Sysstaff auth Installed"; tput sgr0
 ##########################################
-echo " " 
-tput setaf 3;echo "Rebooting Remote Machine"; tput sgr0
-ssh -At -o stricthostkeychecking=no cumorris@$machine_name "sudo reboot"
-
-RESULT_3=$?
-if [ $RESULT_3 -eq 1 ]; then
-    echo " "
-    tput setaf 1;echo "unable to reboot the machine - Something in the auth package may have broke this"; tput sgr0
-    tput setaf 1;echo "I cannot continue, you're on your own br0" ; tput sgr0
-    echo " "
-    exit
-else
-    tput setaf 2;echo "Machine successfully rebooted"; tput sgr0
-fi
-    
+#echo " " 
+#tput setaf 3;echo "Rebooting Remote Machine"; tput sgr0
+#ssh -At -o stricthostkeychecking=no cumorris@$machine_name "sudo reboot"
+#
+#RESULT_3=$?
+#if [ $RESULT_3 -eq 1 ]; then
+#    echo " "
+#    tput setaf 1;echo "unable to reboot the machine - Something in the auth package may have broke this"; tput sgr0
+#    tput setaf 1;echo "I cannot continue, you're on your own br0" ; tput sgr0
+#    echo " "
+#    exit
+#else
+#    tput setaf 2;echo "Machine successfully rebooted"; tput sgr0
+#fi
+#    
 ###########################################
 
 ######################
-tput setaf 2;echo "Machine reboot command executed successfully"; tput sgr0
-tput setaf 3;echo "sleeping for 2 minutes while machine reboots"; tput sgr0
-tput setaf 3;echo "2 mins left...."; tput sgr0
-sleep 1m
-tput setaf 3;echo "1 mins left..."; tput sgr0
-sleep 1m
-tput setaf 3;echo "done sleeping, back to work"; tput sgr0
+#tput setaf 2;echo "Machine reboot command executed successfully"; tput sgr0
+#tput setaf 3;echo "sleeping for 2 minutes while machine reboots"; tput sgr0
+#tput setaf 3;echo "2 mins left...."; tput sgr0
+#sleep 1m
+#tput setaf 3;echo "1 mins left..."; tput sgr0
+#sleep 1m
+#tput setaf 3;echo "done sleeping, back to work"; tput sgr0
 #######################
 
 #########################################
